Update Richards vignette: parameters, fig width, eqnarray
nmfs-ost/ss3-website pull request #17
Opened 2024-12-04 14:32 UTC by arni-magnusson

Minor edits in Richards growth vignette, see
https://github.com/nmfs-ost/ss3-doc/pull/265#issuecomment-2515585375

2024-12-04 14:50 UTC, e-perl-NOAA requested changes

2024-12-04 14:50 UTC, e-perl-NOAA commented on website/qmds/richards_growth_curve.qmd
>           \frac{L_2^b-L_1^b}{1-e^{-k(A_2-A_1)}}\Big]\right)
Could you add \\ after each equation here? Otherwise the quarto website rendering makes it all one line.

2024-12-05 01:30 UTC, arni-magnusson commented
Thank you for your help. I'm not quite sure where the \\ should go, can you elaborate?
The attached screenshot highlights the \\[4ex] that I used to end lines in the equation array, along with the resulting output when I render it in quarto, which seems to look fine.

The tradition in eqnarray seems to be to not end the final line with a \\. Is that the one you're referring to? Happy to tweak these line endings as needed - also feel free to commit those changes if that's easier.

![Screenshot_20241205_114016](https://github.com/user-attachments/assets/5e6ac11b-dcda-4085-a8b0-3fa0cc6a87f3)

2024-12-05 16:50 UTC, e-perl-NOAA approved these changes

2024-12-05 16:51 UTC, e-perl-NOAA commented
Nevermind @arni-magnusson, I see it working now. My quarto was just rendering things incorrectly the first time (where all of those equations were on the same line). It has now rendered correctly

2024-12-05 16:52 UTC, merged